<% project = 'ampr' %>
<% repo = Grit::Repo.new(Rails.root).head.name rescue nil %>
<% dbname = lambda{|env| [project, env, repo].compact.join('_') } %>

defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: sitow
  password: sitow
  host: 127.0.0.1

development: &development
  <<: *defaults
  database: <%= dbname[:development] %>

test: &test
  <<: *defaults
  database: <%= dbname[:test] %>

production:
  <<: *defaults
  database: <%= dbname[:production] %>
